[package]
name = "rust_raytrace"
version = "0.1.0"
authors = ["Calvin Godfrey <calvinbbcard@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.21.1"
rand = "0.7"
image = "0.23.6"
tobj = "2.0.2"